name: Verificar e Remover Duplicados
on: [push]
jobs:
  check-and-remove-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verificar e Remover Duplicados
        run: |
          sort local-zone-refuse.conf | uniq -d > duplicados.txt
          sort local-zone-refuse.conf | uniq > local-zone-refuse-cleaned.conf
          mv local-zone-refuse-cleaned.conf local-zone-refuse.conf
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: duplicados
          path: duplicados.txt
      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add local-zone-refuse.conf
          git commit -m "Remove duplicated entries from local-zone-refuse.conf"
          git push https://${{ secrets.GH_PAT }}@github.com/DidoNael/unbound.git HEAD:main
